### ISSUE TITLE
we need contributors for build platform

### ISSUE THREAD

**Issue by PATILYASHH** [PATILYASHH/sage-Coder#1]
***You Can Contribute This Repo BY Just Solving Simple Issues***

- Find the issues from website
- sudgest new ideas
- add new ideas in website

**Comment by Tarunkumarkanakam** [comment]
I'm interested in contributing, let me know what needs to be done. 😄

**Comment by PATILYASHH** [comment]
I created the platform [Sage Coder](https://sagecoder.vercel.app), a hub designed to provide valuable resources for coders of all levels. On Sage Coder, you'll find tools, coding roadmaps, guides for solving issues, and API platforms that are especially helpful for new programmers, while also being beneficial for experienced developers. The platform is still growing, and I want to make it even more useful by adding new features, options, and tools. However, I can't do this alone. If you can contribute in any way—whether by suggesting improvements, adding content, or developing new features—please consider supporting our open-source project. Your contributions will play a crucial role in making Sage Coder an even better resource for the coding community!
