### ISSUE TITLE
add hackathons to website

### ISSUE THREAD

**Issue by PATILYASHH** [PATILYASHH/sage-Coder#13]

**Comment by Tarunkumarkanakam** [comment]
I want to work on this issue, can I get more information about what needs to be done?

**Comment by PATILYASHH** [comment]
Hello @Tarunkumarkanakam ,

Add hackathon platforms and events (including end dates if needed). I've already created the section for hackathons, so you just need to add this information there. You can work on the issue I've assigned to you

**Comment by Tarunkumarkanakam** [comment]
So, I need to build pages for Hackathon right? From where do I need to get Hackathon information?

**Comment by PATILYASHH** [comment]
> So, I need to build pages for Hackathon right? From where do I need to get Hackathon information?

Google it because I don't know that or you can use chatgpt
